#include QMK_KEYBOARD_H

#include "quantum.h"
#include "action_layer.h"

#define _QWERTY 0
#define _LOWER 1
#define _RAISE 2
#define _GAME 3

#define KC_ KC_TRNS
#define _______ KC_TRNS

#define KC_RST RESET

#define LOWR MO(_LOWER)
#define RASE MO(_RAISE)
#define GAME TO(_GAME)
#define NORM TO(_QWERTY)

#define _LSFT OSM(MOD_LSFT)
#define _SPC_C CTL_T(KC_SPC)
#define _SPC_G GUI_T(KC_SPC)
#define _A_C GUI_T(KC_A)
#define _S_C GUI_T(KC_SCLN)
/* #define _A_C CTL_T(KC_A) */
/* #define _S_C CTL_T(KC_SCLN) */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {


[_QWERTY] = LAYOUT( \
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    GAME,    XXXXXXX, XXXXXXX,        GAME,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSPC, XXXXXXX, XXXXXXX, \
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_F,    KC_TAB,  XXXXXXX, XXXXXXX,        KC_BSPC, KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC, XXXXXXX, XXXXXXX, \
    KC_ESC,  _A_C,    KC_S,    KC_D,    KC_T,    KC_G,    KC_ESC,  XXXXXXX, XXXXXXX,        KC_ENT,  KC_H,    KC_J,    KC_K,    KC_L,    _S_C,    KC_ENT,  XXXXXXX, XXXXXXX, \
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_LSFT, XXXXXXX, XXXXXXX,        KC_RALT, KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RALT, XXXXXXX, XXXXXXX, \
    KC_LALT, KC_LSFT, KC_LCTL, RASE,    LOWR,    KC_LCTL, KC_LGUI, XXXXXXX, XXXXXXX,        KC_LGUI, KC_SPC,  _LSFT,   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX \
),

[_LOWER] = LAYOUT( \
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_0,    XXXXXXX, XXXXXXX,        KC_BSPC, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_ESC,  XXXXXXX, XXXXXXX, \
    KC_TAB,  KC_QUES, KC_MINS, KC_ASTR, KC_PLUS, XXXXXXX, KC_BSPC, XXXXXXX, XXXXXXX,        KC_BSPC, XXXXXXX, KC_LABK, KC_RABK, KC_MINS, KC_P,    KC_TAB,  XXXXXXX, XXXXXXX, \
    KC_ESC,  KC_CIRC, KC_AT,   KC_PERC, KC_QUOT, KC_DLR,  KC_ENT,  XXXXXXX, XXXXXXX,        KC_ENT,  KC_LBRC, KC_LPRN, KC_RPRN, KC_RBRC, KC_COLN, KC_EQL,  XXXXXXX, XXXXXXX, \
    KC_LSFT, KC_TILD, KC_GRV,  KC_HASH, KC_DQUO, KC_PIPE, XXXXXXX, XXXXXXX, XXXXXXX,        KC_RALT, KC_AMPR, KC_LCBR, KC_RCBR, KC_UNDS, KC_BSLS, KC_LALT, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        KC_RGHT, KC_UNDS, KC_UNDS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX \
),

[_RAISE] = LAYOUT( \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        KC_BSPC, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   XXXXXXX, XXXXXXX, XXXXXXX,        KC_BSPC, KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX, XXXXXXX, XXXXXXX,        KC_ENT,  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, KC_MPRV, KC_MNXT, KC_MPLY, XXXXXXX, XXXXXXX, XXXXXXX,        KC_RALT, KC_PAUS, KC_VOLD, KC_VOLU, KC_PAUS, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        KC_RGHT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX \
),

[_GAME] = LAYOUT( \
    KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    NORM,    XXXXXXX, XXXXXXX,        NORM,    KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_BSPC, XXXXXXX, XXXXXXX, \
    KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_F,    KC_TAB,  XXXXXXX, XXXXXXX,        KC_BSPC, KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSPC, XXXXXXX, XXXXXXX, \
    KC_ESC,  KC_A,    KC_S,    KC_D,    KC_T,    KC_G,    KC_ESC,  XXXXXXX, XXXXXXX,        KC_ENT,  KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_ENT,  XXXXXXX, XXXXXXX, \
    KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_LSFT, XXXXXXX, XXXXXXX,        KC_RALT, KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RALT, XXXXXXX, XXXXXXX, \
    KC_LALT, KC_LSFT, KC_LCTL, KC_TAB,  KC_SPC,  KC_LCTL, KC_LGUI, XXXXXXX, XXXXXXX,        KC_LGUI, KC_SPC,  _LSFT,   KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX, XXXXXXX, \
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,        XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX \
)
};
